services:
  datafusion:
    build:
      context: .
      dockerfile: ./docker/Dockerfile 
    container_name: datafusion
    stdin_open: true   
    tty: true    
    volumes:
      - ./docker/shared:/workspace/shared
    restart: unless-stopped
    networks:
      - standard

networks:
  standard:
    driver: bridge