services:
  benchmark:
    build:
      context: ./docker
      dockerfile: ./Dockerfile 
    container_name: benchmark
    stdin_open: true   
    tty: true    
    volumes:
      - ./docker/shared:/workspace/shared
    networks:
      - standard

networks:
  standard:
    driver: bridge