services:
  datafusion:
    build:
      context: .
      dockerfile: ./docker/datafusion/Dockerfile 
    container_name: datafusion
    stdin_open: true   
    tty: true    
    volumes:
      - ./shared:/workspace/shared
    restart: unless-stopped
    networks:
      - standard

networks:
  standard:
    driver: bridge